### ISSUE TITLE
Test SDK on older go version

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/client-sdk-go#190]
We should test our SDK on older version of go (at least) go1.15.

We should remove requirement for go1.19 from top of README and add requirement for go1.18 to CONTRIBUTING.md for devs contributing and needing to support go.mod

**Comment by pgautier404** [comment]
I tested our examples with go1.16, which was the oldest version I could easily co-install and which went EOL 11 months ago. The examples ran without error under this version. However, trying to run the tests, I ran into the following version errors:

```
# github.com/onsi/gomega/internal
../../go/pkg/mod/github.com/onsi/gomega@v1.26.0/internal/polling_signal_error.go:19:33: undefined: any
../../go/pkg/mod/github.com/onsi/gomega@v1.26.0/internal/polling_signal_error.go:40:14: undefined: any
../../go/pkg/mod/github.com/onsi/gomega@v1.26.0/internal/polling_signal_error.go:56:65: undefined: any
note: module requires Go 1.18
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall.go:83:16: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_darwin.go:95:8: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.5.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
```

I assume this is ok given the suggestion to add a minimum requirement of go1.18 for contributing.

I wasn't able to remove the minimum language version directive because a default minimum version is added to the `go.mod` file during CI which later flags the PR for failure in a subsequent linting step. I instead decreased the minimum version required to 1.16, which is the assumed default minimum as of go v1.17. Currently this setup is failing CI linting in a way I cannot reproduce locally.

**Comment by pgautier404** [comment]
https://github.com/momentohq/client-sdk-go/pull/244 closes this issue with more details.
